### ISSUE TITLE
bug: aws_s3_buckets node fields incorrectly discovered

### ISSUE THREAD

**Issue by smokentar** [cloudquery/cloudquery#12393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Affected fields of the `aws_s3_buckets` node:

- block_public_acls
- block_public_policy
- ignore_public_acls
- restrict_public_buckets

When an S3 bucket is created it comes, by default, with these settings enabled. 
The API which CloudQuery is using to fetch this information doesn't pick this up as they are always reported as `false`.
I have discovered that if I manually disable and then re-enable these rules, CloudQuery will then report them correctly as `true`.
We first need to check what API is being used under the hood to fetch this information and understand if it's an issue with the API or with CloudQuery.

### Expected Behavior

The fields mentioned above are reported correctly as `true` without the need to disabled and re-enable them on AWS side.

### CloudQuery (redacted) config

```
kind: source
spec:
  name: "aws"
  registry: "github"
  path: "cloudquery/aws"
  version: "v19.2.0"
  tables: ["*"]
  skip_tables:
    - aws_ec2_vpc_endpoint_services
    - aws_cloudtrail_events
    - aws_docdb_cluster_parameter_groups
    - aws_docdb_engine_versions
    - aws_ec2_instance_types
    - aws_elasticache_engine_versions
    - aws_elasticache_parameter_groups
    - aws_elasticache_reserved_cache_nodes_offerings
    - aws_elasticache_service_updates
    - aws_elasticsearch_versions
    - aws_neptune_cluster_parameter_groups
    - aws_neptune_db_parameter_groups
    - aws_rds_cluster_parameters
    - aws_rds_cluster_parameter_groups
    - aws_rds_cluster_parameter_group_parameters
    - aws_rds_db_parameter_groups
    - aws_rds_engine_versions
    - aws_servicequotas_services
    - aws_servicequotas_quotas
    - aws_iam_role_last_accessed_details
    - aws_iam_user_last_accessed_details
    - aws_iam_policy_last_accessed_details
    - aws_directconnect_locations
    - aws_ram_resource_types
    - aws_lambda_runtimes
    - aws_docdb_event_categories
  destinations: ["neo4j"]
  spec:
    accounts:
      - id: "${ACCOUNT_ID}"
        role_arn: "${ROLE_ARN}"
        role_session_name: "Discovery"
    aws_debug: false

kind: destination
spec:
  name: "neo4j"
  registry: "github"
  path: "cloudquery/neo4j"
  version: "v4.0.1"
  # batch_size: 10000 # optional
  # batch_size_bytes: 5242880 # optional
  spec:
    connection_string: "${DB_ENDPOINT}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
```

### Steps To Reproduce

1. Create an S3 bucket
2. Verify that under `Properties`, `Block all public access` is set to `on` and all 4 fields are ticked.
3. Run a CloudQuery sync
4. Examine the results - the 4 fields will be reported as `false`
5. Go back to AWS, disable and re-enable the `Block all public access` setting
6. Run a second CloudQuery sync
7. Examine the results - the 4 fields will now be reported as `true`

### CloudQuery (redacted) logs

```
{
    "rows": [
        {
            "_cq_id": "079b0863-b411-4411-8312-30a391dbe28a",
            "_cq_source_name": "aws",
            "_cq_sync_time": "2023-07-05T12:09:28.805772Z",
            "account_id": "<some_account>",
            "arn": "<some_bucket_arn>",
            "block_public_acls": false,    <- THIS
            "block_public_policy": false,    <- THIS
            "creation_date": "2023-05-10T12:52:41Z",
            "ignore_public_acls": false,    <- THIS
            "name": "<some_bucket_name",
            "policy": "{}",
            "region": "us-east-1",
            "replication_rules": "[]",
            "restrict_public_buckets": false,    <- THIS
            "tags": "{}",
            "versioning_mfa_delete": "",
            "versioning_status": ""
        }
    ]
}
```

### CloudQuery version

v3.8.0

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by jsoncow** [comment]
Via aws cli `s3api get-public-access-block` for the bucket, yields true values.  

 aws s3api get-public-access-block --bucket s3-bucket
{
    "PublicAccessBlockConfiguration": {
        "BlockPublicAcls": true,
        "IgnorePublicAcls": true,
        "BlockPublicPolicy": true,
        "RestrictPublicBuckets": true
    }
}

In CQ, I see false values for the same bucket and for the 4 properties.

**Comment by disq** [comment]
Hi. Are you sure it's successfully resolving the properties? There seems to be an issue with the current version where the extra properties default to 'false' when they are not resolved. We're planning to address that with #12432 so that if the resolver fails (because of access or other reasons) the values default to `null` instead.

**Comment by disq** [comment]
@smokentar This fix was released in aws [v22.0.1](https://github.com/cloudquery/cloudquery/pull/12434) can you take a look and report what the fields now look like? If they're `null` then you should find the error message in the logs.

**Comment by smokentar** [comment]
Thanks @disq 
I can confirm these 4 fields are now `null`.

I'm running CloudQuery with `--log-console` and `--log-level trace`.
Also I have `aws_debug: true` in the config.

Restricting a discovery to only aws_s3_buckets I'm still unable to find any error.

I have also noticed something new - after 2 buckets, the sync is no longer detecting the properties of next buckets.

Example: (`GET /?publicAccessBlock= HTTP/1.1`)

I have a total of 4 buckets with 2 previously having that manual edit and now being correctly discovered as `true`.
The logs were showing only 2 entries for `GET /?publicAccessBlock= HTTP/1.1` - 1 for `arn_1` and 1 for `arn_2`.
I did a manual edit of another bucket, which **should** resolve the problem, so now we **should** have 3 buckets correctly discovered as `true`.
However we still have only 2 buckets with `true` and 4 entries for `GET /?publicAccessBlock= HTTP/1.1` - 2 for `arn_1` and 2 for `arn_2`.

```
2023-07-24T09:55:27Z DBG Request
GET /?publicAccessBlock= HTTP/1.1
Host: <arn_1>.s3.us-east-1.amazonaws.com

2023-07-24T09:55:29Z DBG Request
GET /?publicAccessBlock= HTTP/1.1
Host: <arn_2>.s3.us-east-1.amazonaws.com

2023-07-24T09:56:13Z DBG Request
GET /?publicAccessBlock= HTTP/1.1
Host: <arn_1>.s3.us-east-1.amazonaws.com

2023-07-24T09:56:15Z DBG Request
GET /?publicAccessBlock= HTTP/1.1
Host: <arn_2>.s3.us-east-1.amazonaws.com
```

I now see GET requests but for only 2 bucket arns (the ones that are already discovered as true due to a previous manual edit).

What I've also noticed is that for the buckets where I haven't done the manual edit there are 9 GET requests but for the buckets where I have - 14 GET requests. 

14:
```
GET /?location= HTTP/1.1
GET /?logging= HTTP/1.1
GET /?policy= HTTP/1.1
GET /?policyStatus= HTTP/1.1
GET /?versioning= HTTP/1.1
GET /?publicAccessBlock= HTTP/1.1
GET /?replication= HTTP/1.1
GET /?tagging= HTTP/1.1
GET /?ownershipControls= HTTP/1.1
GET /?cors= HTTP/1.1
GET /?lifecycle= HTTP/1.1
GET /?website= HTTP/1.1
GET /?encryption= HTTP/1.1
GET /?acl= HTTP/1.1
```

9: 
```
GET /?location= HTTP/1.1
GET /?logging= HTTP/1.1
GET /?policy= HTTP/1.1
GET /?policyStatus= HTTP/1.1
GET /?cors= HTTP/1.1
GET /?lifecycle= HTTP/1.1
GET /?website= HTTP/1.1
GET /?encryption= HTTP/1.1
GET /?acl= HTTP/1.1
```

Missing:
```
GET /?versioning= HTTP/1.1
GET /?publicAccessBlock= HTTP/1.1
GET /?replication= HTTP/1.1
GET /?tagging= HTTP/1.1
GET /?ownershipControls= HTTP/1.1
```

I'm not sure if these are now 2 problems bundled into one.
I'll continue to look why this might be happening but so far I haven't reached any conclusion.

**Comment by disq** [comment]
@smokentar Thanks for the detailed report, I think I know what's going on.

**Comment by smokentar** [comment]
Thanks for looking into it @disq, I wouldn't have figured it's the exception handling
I'll test once this is released

**Comment by disq** [comment]
@smokentar [v22.1.0](https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-aws-v22.1.0) is now released 🎉

**Comment by smokentar** [comment]
I can confirm buckets are now correctly discovered, all have the full amount of GET requests and logging correctly indicates that.

Thanks for the quick resolution @disq!
